services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./.env
    environment:
      FRONTEND_ORIGIN: ${FRONTEND_ORIGIN:-http://localhost:5173}
      OPENAI_TRANSCRIPTION_MODEL: ${OPENAI_TRANSCRIPTION_MODEL:-whisper-1}
      STOCKFISH_PATH: ${STOCKFISH_PATH:-}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-http://localhost:8000}
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped
